# Generated by Django 4.2.8 on 2026-01-10 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0003_aluno_foto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota1', models.DecimalField(decimal_places=1, default=0, max_digits=3)),
                ('nota2', models.DecimalField(decimal_places=1, default=0, max_digits=3)),
                ('nota3', models.DecimalField(decimal_places=1, default=0, max_digits=3)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('matricula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='escola.matricula')),
            ],
        ),
    ]
