# Generated by Django 4.2.8 on 2026-01-10 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0004_avaliacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='AtividadeAvaliativa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('A', 'Atividade'), ('P', 'Prova'), ('T', 'Trabalho')], default='A', max_length=1)),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField(blank=True)),
                ('nota', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('data_entrega', models.DateField(blank=True, null=True)),
                ('entregue', models.BooleanField(default=False)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('matricula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atividades', to='escola.matricula')),
            ],
            options={
                'ordering': ['-data_criacao'],
            },
        ),
    ]
